// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgRMyhBkKofJFi38zA1h7eJYKS8_S48qA',
    appId: '1:613638259363:web:91f376b7a534b53e543516',
    messagingSenderId: '613638259363',
    projectId: 'book-me-app-1f310',
    authDomain: 'book-me-app-1f310.firebaseapp.com',
    storageBucket: 'book-me-app-1f310.firebasestorage.app',
    measurementId: 'G-WCWD7777GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRuzFxQldxyUXntDvQzbF-JNMjl4H7Qw',
    appId: '1:613638259363:android:651ffd38d4f7a733543516',
    messagingSenderId: '613638259363',
    projectId: 'book-me-app-1f310',
    storageBucket: 'book-me-app-1f310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHFkH-JKtGRjdlAvH9WhaLRLHMYz3NssU',
    appId: '1:613638259363:ios:226e533ba2623248543516',
    messagingSenderId: '613638259363',
    projectId: 'book-me-app-1f310',
    storageBucket: 'book-me-app-1f310.firebasestorage.app',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHFkH-JKtGRjdlAvH9WhaLRLHMYz3NssU',
    appId: '1:613638259363:ios:226e533ba2623248543516',
    messagingSenderId: '613638259363',
    projectId: 'book-me-app-1f310',
    storageBucket: 'book-me-app-1f310.firebasestorage.app',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgRMyhBkKofJFi38zA1h7eJYKS8_S48qA',
    appId: '1:613638259363:web:22254df71a81e0a2543516',
    messagingSenderId: '613638259363',
    projectId: 'book-me-app-1f310',
    authDomain: 'book-me-app-1f310.firebaseapp.com',
    storageBucket: 'book-me-app-1f310.firebasestorage.app',
    measurementId: 'G-QGB1ZWMGNT',
  );
}
